@baseUrl = http://localhost:8080

# /USERS

    ### 
    POST {{baseUrl}}/users
    content-type: application/json

    {
        "name": "sample17",
        "age": 21
    }
    ###

    ###
    GET {{baseUrl}}/users
    ###

    ###
    PUT {{baseUrl}}/users/11
    content-type: application/json

    {
        "name": "Marcelo 20",
        "age": 14
    }
    ###

    ###
    DELETE {{baseUrl}}/users/3

    ###
# /POSTS
    ###
    GET {{baseUrl}}/users/6/posts
    followerId: 99
    
    ###
    GET {{baseUrl}}/users/99/posts

    ###
    POST {{baseUrl}}/users/7/posts
    Content-Type: application/json

    {
        "text": "Está sendo ótimo"
    }
    ###
    ###
    POST {{baseUrl}}/users/6/posts
    Content-Type: application/json

    {
        "text": "Segundo post"
    }


# /FOLLOWES
    ###
    GET {{baseUrl}}/users/6/followers
    ###
    GET {{baseUrl}}/users/1/followers
    ###
    PUT {{baseUrl}}/users/6/followers
    Content-Type: application/json

    {
        "followerId": 17
    }
    ###
    DELETE {{baseUrl}}/users/6/followers?followerId=11
